// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BookFast.Facility.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccommodationRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        public AccommodationRepresentation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        /// <param name="id">Accommodation ID</param>
        /// <param name="facilityId">Facility ID</param>
        /// <param name="name">Accommodation name</param>
        /// <param name="description">Accommodation description</param>
        /// <param name="roomCount">Number of rooms</param>
        /// <param name="images">Accommodation images</param>
        public AccommodationRepresentation(System.Guid? id = default(System.Guid?), System.Guid? facilityId = default(System.Guid?), string name = default(string), string description = default(string), int? roomCount = default(int?), IList<string> images = default(IList<string>))
        {
            Id = id;
            FacilityId = facilityId;
            Name = name;
            Description = description;
            RoomCount = roomCount;
            Images = images;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets accommodation ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets facility ID
        /// </summary>
        [JsonProperty(PropertyName = "facilityId")]
        public System.Guid? FacilityId { get; set; }

        /// <summary>
        /// Gets or sets accommodation name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets accommodation description
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets number of rooms
        /// </summary>
        [JsonProperty(PropertyName = "roomCount")]
        public int? RoomCount { get; set; }

        /// <summary>
        /// Gets or sets accommodation images
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<string> Images { get; set; }

    }
}
