// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Booking.Client.Models
{
    using System.Linq;

    public partial class BookingData
    {
        /// <summary>
        /// Initializes a new instance of the BookingData class.
        /// </summary>
        public BookingData() { }

        /// <summary>
        /// Initializes a new instance of the BookingData class.
        /// </summary>
        /// <param name="fromDate">Booking start date</param>
        /// <param name="toDate">Booking end date</param>
        /// <param name="accommodationId">Accommodation ID</param>
        public BookingData(System.DateTime fromDate, System.DateTime toDate, System.Guid? accommodationId = default(System.Guid?))
        {
            AccommodationId = accommodationId;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// Gets or sets accommodation ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "accommodationId")]
        public System.Guid? AccommodationId { get; set; }

        /// <summary>
        /// Gets or sets booking start date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fromDate")]
        public System.DateTime FromDate { get; set; }

        /// <summary>
        /// Gets or sets booking end date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "toDate")]
        public System.DateTime ToDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
