// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BookFast.Booking.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BookingData
    {
        /// <summary>
        /// Initializes a new instance of the BookingData class.
        /// </summary>
        public BookingData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BookingData class.
        /// </summary>
        /// <param name="fromDate">Booking start date</param>
        /// <param name="toDate">Booking end date</param>
        /// <param name="accommodationId">Accommodation ID</param>
        public BookingData(System.DateTime fromDate, System.DateTime toDate, int? accommodationId = default(int?))
        {
            AccommodationId = accommodationId;
            FromDate = fromDate;
            ToDate = toDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets accommodation ID
        /// </summary>
        [JsonProperty(PropertyName = "accommodationId")]
        public int? AccommodationId { get; set; }

        /// <summary>
        /// Gets or sets booking start date
        /// </summary>
        [JsonProperty(PropertyName = "fromDate")]
        public System.DateTime FromDate { get; set; }

        /// <summary>
        /// Gets or sets booking end date
        /// </summary>
        [JsonProperty(PropertyName = "toDate")]
        public System.DateTime ToDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
