// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BookFast.Booking.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BookAccommodationCommand
    {
        /// <summary>
        /// Initializes a new instance of the BookAccommodationCommand class.
        /// </summary>
        public BookAccommodationCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BookAccommodationCommand class.
        /// </summary>
        public BookAccommodationCommand(System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?))
        {
            FromDate = fromDate;
            ToDate = toDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "fromDate")]
        public System.DateTime? FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "toDate")]
        public System.DateTime? ToDate { get; set; }

    }
}
