// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Booking.Client.Models
{
    using System.Linq;

    public partial class BookingRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the BookingRepresentation class.
        /// </summary>
        public BookingRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the BookingRepresentation class.
        /// </summary>
        /// <param name="id">Booking ID</param>
        /// <param name="accommodationId">Accommodation ID</param>
        /// <param name="accommodationName">Accommodation name</param>
        /// <param name="facilityId">Facility ID</param>
        /// <param name="facilityName">Facility name</param>
        /// <param name="streetAddress">Facility street address</param>
        /// <param name="fromDate">Booking start date</param>
        /// <param name="toDate">Booking end date</param>
        public BookingRepresentation(System.Guid? id = default(System.Guid?), System.Guid? accommodationId = default(System.Guid?), string accommodationName = default(string), System.Guid? facilityId = default(System.Guid?), string facilityName = default(string), string streetAddress = default(string), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?))
        {
            Id = id;
            AccommodationId = accommodationId;
            AccommodationName = accommodationName;
            FacilityId = facilityId;
            FacilityName = facilityName;
            StreetAddress = streetAddress;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// Gets or sets booking ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets accommodation ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "accommodationId")]
        public System.Guid? AccommodationId { get; set; }

        /// <summary>
        /// Gets or sets accommodation name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "accommodationName")]
        public string AccommodationName { get; set; }

        /// <summary>
        /// Gets or sets facility ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "facilityId")]
        public System.Guid? FacilityId { get; set; }

        /// <summary>
        /// Gets or sets facility name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "facilityName")]
        public string FacilityName { get; set; }

        /// <summary>
        /// Gets or sets facility street address
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "streetAddress")]
        public string StreetAddress { get; set; }

        /// <summary>
        /// Gets or sets booking start date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fromDate")]
        public System.DateTime? FromDate { get; set; }

        /// <summary>
        /// Gets or sets booking end date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "toDate")]
        public System.DateTime? ToDate { get; set; }

    }
}
