// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Web.Proxy.Models
{
    using System.Linq;

    public partial class AccommodationRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        public AccommodationRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        /// <param name="id">Accommodation ID</param>
        /// <param name="facilityId">Facility ID</param>
        /// <param name="name">Accommodation name</param>
        /// <param name="description">Accommodation description</param>
        /// <param name="roomCount">Number of rooms</param>
        /// <param name="images">Accommodation images</param>
        public AccommodationRepresentation(System.Guid? id = default(System.Guid?), System.Guid? facilityId = default(System.Guid?), string name = default(string), string description = default(string), int? roomCount = default(int?), System.Collections.Generic.IList<string> images = default(System.Collections.Generic.IList<string>))
        {
            Id = id;
            FacilityId = facilityId;
            Name = name;
            Description = description;
            RoomCount = roomCount;
            Images = images;
        }

        /// <summary>
        /// Gets or sets accommodation ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets facility ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "facilityId")]
        public System.Guid? FacilityId { get; set; }

        /// <summary>
        /// Gets or sets accommodation name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets accommodation description
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets number of rooms
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "roomCount")]
        public int? RoomCount { get; set; }

        /// <summary>
        /// Gets or sets accommodation images
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "images")]
        public System.Collections.Generic.IList<string> Images { get; set; }

    }
}
