// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Web.Proxy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AccommodationRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        public AccommodationRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the AccommodationRepresentation
        /// class.
        /// </summary>
        public AccommodationRepresentation(Guid? id = default(Guid?), Guid? facilityId = default(Guid?), string name = default(string), string description = default(string), int? roomCount = default(int?), IList<string> images = default(IList<string>))
        {
            Id = id;
            FacilityId = facilityId;
            Name = name;
            Description = description;
            RoomCount = roomCount;
            Images = images;
        }

        /// <summary>
        /// Accommodation ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Facility ID
        /// </summary>
        [JsonProperty(PropertyName = "facilityId")]
        public Guid? FacilityId { get; set; }

        /// <summary>
        /// Accommodation name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Accommodation description
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Number of rooms
        /// </summary>
        [JsonProperty(PropertyName = "roomCount")]
        public int? RoomCount { get; set; }

        /// <summary>
        /// Accommodation images
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<string> Images { get; set; }

    }
}
