// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Web.Proxy.Models
{
    using System.Linq;

    public partial class SearchResult
    {
        /// <summary>
        /// Initializes a new instance of the SearchResult class.
        /// </summary>
        public SearchResult() { }

        /// <summary>
        /// Initializes a new instance of the SearchResult class.
        /// </summary>
        public SearchResult(double? score = default(double?), System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>> highlights = default(System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>>), System.Collections.Generic.IDictionary<string, object> document = default(System.Collections.Generic.IDictionary<string, object>))
        {
            Score = score;
            Highlights = highlights;
            Document = document;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "highlights")]
        public System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>> Highlights { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "document")]
        public System.Collections.Generic.IDictionary<string, object> Document { get; set; }

    }
}
