// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Files.Client.Models
{
    using System.Linq;

    public partial class FileAccessTokenRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the FileAccessTokenRepresentation
        /// class.
        /// </summary>
        public FileAccessTokenRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the FileAccessTokenRepresentation
        /// class.
        /// </summary>
        /// <param name="accessPermission">Possible values include: 'Read',
        /// 'Write', 'Delete'</param>
        public FileAccessTokenRepresentation(string accessPermission = default(string), string url = default(string))
        {
            AccessPermission = accessPermission;
            Url = url;
        }

        /// <summary>
        /// Gets or sets possible values include: 'Read', 'Write', 'Delete'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "accessPermission")]
        public string AccessPermission { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
